### ISSUE TITLE
About "Client ID"

### ISSUE THREAD

**Issue by sparrowhe** [vatsimnetwork/documentation#1]
Where can I find my client id? When I register a new site, I only get a "saftey key"

**Comment by nepetadosmil** [comment]
It's the number just to the left of your client secret/safety key

**Comment by Eureka0225** [comment]
My saftey key didn't include any numbers

**Comment by nepetadosmil** [comment]
Is the question about Connect (new login system) or about the API? If it is about Connect, please do look carefully again. Open your application, go to the clients section and look to the far left in the row 🙂
